export interface DialCode {
  code: string;
  iso: string;
  name: string;
  digits: number;
}

export const DIAL_CODES: DialCode[] = [
  { code: "+93",  iso: "AF", name: "Afghanistan", digits: 9  },
  { code: "+355", iso: "AL", name: "Albania", digits: 9  },
  { code: "+213", iso: "DZ", name: "Algeria", digits: 9  },
  { code: "+1684",iso: "AS", name: "American Samoa", digits: 10 },
  { code: "+376", iso: "AD", name: "Andorra", digits: 6  },
  { code: "+244", iso: "AO", name: "Angola", digits: 9  },
  { code: "+1264",iso: "AI", name: "Anguilla", digits: 10 },
  { code: "+1268",iso: "AG", name: "Antigua and Barbuda", digits: 10 },
  { code: "+54",  iso: "AR", name: "Argentina", digits: 10 },
  { code: "+374", iso: "AM", name: "Armenia", digits: 8  },
  { code: "+297", iso: "AW", name: "Aruba", digits: 7  },
  { code: "+61",  iso: "AU", name: "Australia", digits: 9  },
  { code: "+43",  iso: "AT", name: "Austria", digits: 10 },
  { code: "+994", iso: "AZ", name: "Azerbaijan", digits: 9  },
  { code: "+1242",iso: "BS", name: "Bahamas", digits: 10 },
  { code: "+973", iso: "BH", name: "Bahrain", digits: 8  },
  { code: "+880", iso: "BD", name: "Bangladesh", digits: 10 },
  { code: "+1246",iso: "BB", name: "Barbados", digits: 10 },
  { code: "+375", iso: "BY", name: "Belarus", digits: 9  },
  { code: "+32",  iso: "BE", name: "Belgium", digits: 9  },
  { code: "+501", iso: "BZ", name: "Belize", digits: 7  },
  { code: "+229", iso: "BJ", name: "Benin", digits: 8  },
  { code: "+1441",iso: "BM", name: "Bermuda", digits: 10 },
  { code: "+975", iso: "BT", name: "Bhutan", digits: 8  },
  { code: "+591", iso: "BO", name: "Bolivia", digits: 8  },
  { code: "+387", iso: "BA", name: "Bosnia and Herzegovina", digits: 8  },
  { code: "+267", iso: "BW", name: "Botswana", digits: 7  },
  { code: "+55",  iso: "BR", name: "Brazil", digits: 11 },
  { code: "+246", iso: "IO", name: "British Indian Ocean Territory", digits: 7  },
  { code: "+1284",iso: "VG", name: "British Virgin Islands", digits: 10 },
  { code: "+673", iso: "BN", name: "Brunei", digits: 7  },
  { code: "+359", iso: "BG", name: "Bulgaria", digits: 9  },
  { code: "+226", iso: "BF", name: "Burkina Faso", digits: 8  },
  { code: "+257", iso: "BI", name: "Burundi", digits: 8  },
  { code: "+855", iso: "KH", name: "Cambodia", digits: 9  },
  { code: "+237", iso: "CM", name: "Cameroon", digits: 9  },
  { code: "+1",   iso: "CA", name: "Canada", digits: 10 },
  { code: "+238", iso: "CV", name: "Cape Verde", digits: 7  },
  { code: "+1345",iso: "KY", name: "Cayman Islands", digits: 10 },
  { code: "+236", iso: "CF", name: "Central African Republic", digits: 8  },
  { code: "+235", iso: "TD", name: "Chad", digits: 8  },
  { code: "+56",  iso: "CL", name: "Chile", digits: 9  },
  { code: "+86",  iso: "CN", name: "China", digits: 11 },
  { code: "+57",  iso: "CO", name: "Colombia", digits: 10 },
  { code: "+269", iso: "KM", name: "Comoros", digits: 7  },
  { code: "+242", iso: "CG", name: "Congo", digits: 9  },
  { code: "+243", iso: "CD", name: "Congo (DRC)", digits: 9  },
  { code: "+682", iso: "CK", name: "Cook Islands", digits: 5  },
  { code: "+506", iso: "CR", name: "Costa Rica", digits: 8  },
  { code: "+385", iso: "HR", name: "Croatia", digits: 9  },
  { code: "+53",  iso: "CU", name: "Cuba", digits: 8  },
  { code: "+357", iso: "CY", name: "Cyprus", digits: 8  },
  { code: "+420", iso: "CZ", name: "Czech Republic", digits: 9  },
  { code: "+45",  iso: "DK", name: "Denmark", digits: 8  },
  { code: "+253", iso: "DJ", name: "Djibouti", digits: 8  },
  { code: "+1767",iso: "DM", name: "Dominica", digits: 10 },
  { code: "+1809",iso: "DO", name: "Dominican Republic", digits: 10 },
  { code: "+593", iso: "EC", name: "Ecuador", digits: 9  },
  { code: "+20",  iso: "EG", name: "Egypt", digits: 10 },
  { code: "+503", iso: "SV", name: "El Salvador", digits: 8  },
  { code: "+240", iso: "GQ", name: "Equatorial Guinea", digits: 9  },
  { code: "+291", iso: "ER", name: "Eritrea", digits: 7  },
  { code: "+372", iso: "EE", name: "Estonia", digits: 8  },
  { code: "+268", iso: "SZ", name: "Eswatini", digits: 8  },
  { code: "+251", iso: "ET", name: "Ethiopia", digits: 9  },
  { code: "+500", iso: "FK", name: "Falkland Islands", digits: 5  },
  { code: "+298", iso: "FO", name: "Faroe Islands", digits: 6  },
  { code: "+679", iso: "FJ", name: "Fiji", digits: 7  },
  { code: "+358", iso: "FI", name: "Finland", digits: 10 },
  { code: "+33",  iso: "FR", name: "France", digits: 9  },
  { code: "+594", iso: "GF", name: "French Guiana", digits: 9  },
  { code: "+689", iso: "PF", name: "French Polynesia", digits: 8  },
  { code: "+241", iso: "GA", name: "Gabon", digits: 7  },
  { code: "+220", iso: "GM", name: "Gambia", digits: 7  },
  { code: "+995", iso: "GE", name: "Georgia", digits: 9  },
  { code: "+49",  iso: "DE", name: "Germany", digits: 11 },
  { code: "+233", iso: "GH", name: "Ghana", digits: 9  },
  { code: "+350", iso: "GI", name: "Gibraltar", digits: 8  },
  { code: "+30",  iso: "GR", name: "Greece", digits: 10 },
  { code: "+299", iso: "GL", name: "Greenland", digits: 6  },
  { code: "+1473",iso: "GD", name: "Grenada", digits: 10 },
  { code: "+590", iso: "GP", name: "Guadeloupe", digits: 9  },
  { code: "+1671",iso: "GU", name: "Guam", digits: 10 },
  { code: "+502", iso: "GT", name: "Guatemala", digits: 8  },
  { code: "+44",  iso: "GG", name: "Guernsey", digits: 10 },
  { code: "+224", iso: "GN", name: "Guinea", digits: 9  },
  { code: "+245", iso: "GW", name: "Guinea-Bissau", digits: 7  },
  { code: "+592", iso: "GY", name: "Guyana", digits: 7  },
  { code: "+509", iso: "HT", name: "Haiti", digits: 8  },
  { code: "+504", iso: "HN", name: "Honduras", digits: 8  },
  { code: "+852", iso: "HK", name: "Hong Kong", digits: 8  },
  { code: "+36",  iso: "HU", name: "Hungary", digits: 9  },
  { code: "+354", iso: "IS", name: "Iceland", digits: 7  },
  { code: "+91",  iso: "IN", name: "India", digits: 10 },
  { code: "+62",  iso: "ID", name: "Indonesia", digits: 11 },
  { code: "+98",  iso: "IR", name: "Iran", digits: 10 },
  { code: "+964", iso: "IQ", name: "Iraq", digits: 10 },
  { code: "+353", iso: "IE", name: "Ireland", digits: 9  },
  { code: "+44",  iso: "IM", name: "Isle of Man", digits: 10 },
  { code: "+972", iso: "IL", name: "Israel", digits: 9  },
  { code: "+39",  iso: "IT", name: "Italy", digits: 10 },
  { code: "+225", iso: "CI", name: "Ivory Coast", digits: 8  },
  { code: "+1876",iso: "JM", name: "Jamaica", digits: 10 },
  { code: "+81",  iso: "JP", name: "Japan", digits: 11 },
  { code: "+44",  iso: "JE", name: "Jersey", digits: 10 },
  { code: "+962", iso: "JO", name: "Jordan", digits: 9  },
  { code: "+7",   iso: "KZ", name: "Kazakhstan", digits: 10 },
  { code: "+254", iso: "KE", name: "Kenya", digits: 9  },
  { code: "+686", iso: "KI", name: "Kiribati", digits: 8  },
  { code: "+383", iso: "XK", name: "Kosovo", digits: 8  },
  { code: "+965", iso: "KW", name: "Kuwait", digits: 8  },
  { code: "+996", iso: "KG", name: "Kyrgyzstan", digits: 9  },
  { code: "+856", iso: "LA", name: "Laos", digits: 9  },
  { code: "+371", iso: "LV", name: "Latvia", digits: 8  },
  { code: "+961", iso: "LB", name: "Lebanon", digits: 8  },
  { code: "+266", iso: "LS", name: "Lesotho", digits: 8  },
  { code: "+231", iso: "LR", name: "Liberia", digits: 8  },
  { code: "+218", iso: "LY", name: "Libya", digits: 9  },
  { code: "+423", iso: "LI", name: "Liechtenstein", digits: 7  },
  { code: "+370", iso: "LT", name: "Lithuania", digits: 8  },
  { code: "+352", iso: "LU", name: "Luxembourg", digits: 9  },
  { code: "+853", iso: "MO", name: "Macao", digits: 8  },
  { code: "+261", iso: "MG", name: "Madagascar", digits: 9  },
  { code: "+265", iso: "MW", name: "Malawi", digits: 9  },
  { code: "+60",  iso: "MY", name: "Malaysia", digits: 10 },
  { code: "+960", iso: "MV", name: "Maldives", digits: 7  },
  { code: "+223", iso: "ML", name: "Mali", digits: 8  },
  { code: "+356", iso: "MT", name: "Malta", digits: 8  },
  { code: "+692", iso: "MH", name: "Marshall Islands", digits: 7  },
  { code: "+596", iso: "MQ", name: "Martinique", digits: 9  },
  { code: "+222", iso: "MR", name: "Mauritania", digits: 8  },
  { code: "+230", iso: "MU", name: "Mauritius", digits: 8  },
  { code: "+262", iso: "YT", name: "Mayotte", digits: 9  },
  { code: "+52",  iso: "MX", name: "Mexico", digits: 10 },
  { code: "+691", iso: "FM", name: "Micronesia", digits: 7  },
  { code: "+373", iso: "MD", name: "Moldova", digits: 8  },
  { code: "+377", iso: "MC", name: "Monaco", digits: 9  },
  { code: "+976", iso: "MN", name: "Mongolia", digits: 8  },
  { code: "+382", iso: "ME", name: "Montenegro", digits: 8  },
  { code: "+1664",iso: "MS", name: "Montserrat", digits: 10 },
  { code: "+212", iso: "MA", name: "Morocco", digits: 9  },
  { code: "+258", iso: "MZ", name: "Mozambique", digits: 9  },
  { code: "+95",  iso: "MM", name: "Myanmar", digits: 9  },
  { code: "+264", iso: "NA", name: "Namibia", digits: 9  },
  { code: "+674", iso: "NR", name: "Nauru", digits: 7  },
  { code: "+977", iso: "NP", name: "Nepal", digits: 10 },
  { code: "+31",  iso: "NL", name: "Netherlands", digits: 9  },
  { code: "+687", iso: "NC", name: "New Caledonia", digits: 6  },
  { code: "+64",  iso: "NZ", name: "New Zealand", digits: 9  },
  { code: "+505", iso: "NI", name: "Nicaragua", digits: 8  },
  { code: "+227", iso: "NE", name: "Niger", digits: 8  },
  { code: "+234", iso: "NG", name: "Nigeria", digits: 10 },
  { code: "+683", iso: "NU", name: "Niue", digits: 4  },
  { code: "+672", iso: "NF", name: "Norfolk Island", digits: 6  },
  { code: "+850", iso: "KP", name: "North Korea", digits: 9  },
  { code: "+389", iso: "MK", name: "North Macedonia", digits: 8  },
  { code: "+1670",iso: "MP", name: "Northern Mariana Islands", digits: 10 },
  { code: "+47",  iso: "NO", name: "Norway", digits: 8  },
  { code: "+968", iso: "OM", name: "Oman", digits: 8  },
  { code: "+92",  iso: "PK", name: "Pakistan", digits: 10 },
  { code: "+680", iso: "PW", name: "Palau", digits: 7  },
  { code: "+970", iso: "PS", name: "Palestine", digits: 9  },
  { code: "+507", iso: "PA", name: "Panama", digits: 8  },
  { code: "+675", iso: "PG", name: "Papua New Guinea", digits: 8  },
  { code: "+595", iso: "PY", name: "Paraguay", digits: 9  },
  { code: "+51",  iso: "PE", name: "Peru", digits: 9  },
  { code: "+63",  iso: "PH", name: "Philippines", digits: 10 },
  { code: "+48",  iso: "PL", name: "Poland", digits: 9  },
  { code: "+351", iso: "PT", name: "Portugal", digits: 9  },
  { code: "+1787",iso: "PR", name: "Puerto Rico", digits: 10 },
  { code: "+974", iso: "QA", name: "Qatar", digits: 8  },
  { code: "+262", iso: "RE", name: "Réunion", digits: 9  },
  { code: "+40",  iso: "RO", name: "Romania", digits: 9  },
  { code: "+7",   iso: "RU", name: "Russia", digits: 10 },
  { code: "+250", iso: "RW", name: "Rwanda", digits: 9  },
  { code: "+290", iso: "SH", name: "Saint Helena", digits: 4  },
  { code: "+1869",iso: "KN", name: "Saint Kitts and Nevis", digits: 10 },
  { code: "+1758",iso: "LC", name: "Saint Lucia", digits: 10 },
  { code: "+508", iso: "PM", name: "Saint Pierre and Miquelon", digits: 6  },
  { code: "+1784",iso: "VC", name: "Saint Vincent and the Grenadines", digits: 10 },
  { code: "+685", iso: "WS", name: "Samoa", digits: 7  },
  { code: "+378", iso: "SM", name: "San Marino", digits: 10 },
  { code: "+239", iso: "ST", name: "São Tomé and Príncipe", digits: 7  },
  { code: "+966", iso: "SA", name: "Saudi Arabia", digits: 9  },
  { code: "+221", iso: "SN", name: "Senegal", digits: 9  },
  { code: "+381", iso: "RS", name: "Serbia", digits: 9  },
  { code: "+248", iso: "SC", name: "Seychelles", digits: 7  },
  { code: "+232", iso: "SL", name: "Sierra Leone", digits: 8  },
  { code: "+65",  iso: "SG", name: "Singapore", digits: 8  },
  { code: "+1721",iso: "SX", name: "Sint Maarten", digits: 10 },
  { code: "+421", iso: "SK", name: "Slovakia", digits: 9  },
  { code: "+386", iso: "SI", name: "Slovenia", digits: 8  },
  { code: "+677", iso: "SB", name: "Solomon Islands", digits: 7  },
  { code: "+252", iso: "SO", name: "Somalia", digits: 9  },
  { code: "+27",  iso: "ZA", name: "South Africa", digits: 9  },
  { code: "+82",  iso: "KR", name: "South Korea", digits: 10 },
  { code: "+211", iso: "SS", name: "South Sudan", digits: 9  },
  { code: "+34",  iso: "ES", name: "Spain", digits: 9  },
  { code: "+94",  iso: "LK", name: "Sri Lanka", digits: 9  },
  { code: "+249", iso: "SD", name: "Sudan", digits: 9  },
  { code: "+597", iso: "SR", name: "Suriname", digits: 7  },
  { code: "+47",  iso: "SJ", name: "Svalbard and Jan Mayen", digits: 8  },
  { code: "+46",  iso: "SE", name: "Sweden", digits: 9  },
  { code: "+41",  iso: "CH", name: "Switzerland", digits: 9  },
  { code: "+963", iso: "SY", name: "Syria", digits: 9  },
  { code: "+886", iso: "TW", name: "Taiwan", digits: 9  },
  { code: "+992", iso: "TJ", name: "Tajikistan", digits: 9  },
  { code: "+255", iso: "TZ", name: "Tanzania", digits: 9  },
  { code: "+66",  iso: "TH", name: "Thailand", digits: 9  },
  { code: "+670", iso: "TL", name: "Timor-Leste", digits: 8  },
  { code: "+228", iso: "TG", name: "Togo", digits: 8  },
  { code: "+690", iso: "TK", name: "Tokelau", digits: 4  },
  { code: "+676", iso: "TO", name: "Tonga", digits: 5  },
  { code: "+1868",iso: "TT", name: "Trinidad and Tobago", digits: 10 },
  { code: "+216", iso: "TN", name: "Tunisia", digits: 8  },
  { code: "+90",  iso: "TR", name: "Turkey", digits: 10 },
  { code: "+993", iso: "TM", name: "Turkmenistan", digits: 8  },
  { code: "+1649",iso: "TC", name: "Turks and Caicos Islands", digits: 10 },
  { code: "+688", iso: "TV", name: "Tuvalu", digits: 6  },
  { code: "+1340",iso: "VI", name: "U.S. Virgin Islands", digits: 10 },
  { code: "+256", iso: "UG", name: "Uganda", digits: 9  },
  { code: "+380", iso: "UA", name: "Ukraine", digits: 9  },
  { code: "+971", iso: "AE", name: "United Arab Emirates", digits: 9  },
  { code: "+44",  iso: "GB", name: "United Kingdom", digits: 10 },
  { code: "+1",   iso: "US", name: "United States", digits: 10 },
  { code: "+598", iso: "UY", name: "Uruguay", digits: 9  },
  { code: "+998", iso: "UZ", name: "Uzbekistan", digits: 9  },
  { code: "+678", iso: "VU", name: "Vanuatu", digits: 7  },
  { code: "+379", iso: "VA", name: "Vatican City", digits: 10 },
  { code: "+58",  iso: "VE", name: "Venezuela", digits: 10 },
  { code: "+84",  iso: "VN", name: "Vietnam", digits: 9  },
  { code: "+681", iso: "WF", name: "Wallis and Futuna", digits: 6  },
  { code: "+212", iso: "EH", name: "Western Sahara", digits: 9  },
  { code: "+967", iso: "YE", name: "Yemen", digits: 9  },
  { code: "+260", iso: "ZM", name: "Zambia", digits: 9  },
  { code: "+263", iso: "ZW", name: "Zimbabwe", digits: 9  },
];

/**
 * Format raw digit input into a masked phone string based on dial code.
 * US/CA (+1): (XXX) XXX-XXXX
 * UK (+44):   XXXXX XXXXXX
 * Generic:    XXX XXX XXXX
 */
export function formatPhoneNumber(digits: string, dialCode: string): string {
  if (dialCode === "+1") {
    const d = digits.slice(0, 10);
    if (d.length <= 3) return d;
    if (d.length <= 6) return `(${d.slice(0, 3)}) ${d.slice(3)}`;
    return `(${d.slice(0, 3)}) ${d.slice(3, 6)}-${d.slice(6)}`;
  }
  if (dialCode === "+44") {
    const d = digits.slice(0, 11);
    if (d.length <= 5) return d;
    return `${d.slice(0, 5)} ${d.slice(5)}`;
  }
  // Generic: groups of 3-4
  const d = digits.slice(0, 12);
  if (d.length <= 3) return d;
  if (d.length <= 6) return `${d.slice(0, 3)} ${d.slice(3)}`;
  if (d.length <= 10) return `${d.slice(0, 3)} ${d.slice(3, 6)} ${d.slice(6)}`;
  return `${d.slice(0, 3)} ${d.slice(3, 6)} ${d.slice(6, 10)} ${d.slice(10)}`;
}

/** Strip all non-digit characters */
export function extractDigits(value: string): string {
  return value.replace(/\D/g, "");
}
